# Generated by Django 4.1.3 on 2023-02-06 14:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NoteModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('content', models.TextField()),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PolicyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=255)),
                ('leave_type', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('num_of_leaves', models.IntegerField()),
                ('carry_forward', models.IntegerField()),
                ('enchashment', models.IntegerField()),
                ('max_num_cont_leaves', models.IntegerField()),
                ('last_udpated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
