# Generated by Django 4.1.3 on 2023-02-07 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeoff_api', '0002_leavemodel_delete_notemodel'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='policymodel',
            constraint=models.UniqueConstraint(fields=('organization', 'leave_type', 'designation'), name='unique_policy'),
        ),
    ]
